title: ChinPen
description: "Technology, Audio and other Geekery"
logo:           site-logo.png
url:              http://localhost:4000

destination: ./_publish
plugins:     ./_plugins
layouts:     ./_layouts

timezone:    Singapore/Singapore
encoding:    UTF-8

# Owner/author information
owner:
  name:          Chinmay
  avatar:         chinpen.jpg
  email:          chinpen@chinpen.net
  # Social networking links used in footer. Update and remove as you like.
  twitter: ntt
  facebook: chinpen
  github: notthetup

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/

permalink: /:title
markdown: redcarpet

exclude: ["readme.md", "archives", "Gruntfile.js", "package.json", "node_modules", "less"]
