title: ChinPen
description: "Technology, Audio and other Geekery"
logo:           site-logo.png
url:              http://chinpen.net

destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

safe: true

timezone:    Singapore/Singapore
encoding:    UTF-8

disqus_shortname: chinpen

# Owner/author information
owner:
  name:          Chinmay
  avatar:         chinpen.jpg
  email:          chinpen@chinpen.net
  twitter:        ntt
  facebook:   chinpen
  github:       notthetup


  # Analytics and webmaster tools stuff goes here
  google_analytics: UA-12204519-1

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: All Articles
    url: /articles/

permalink: /:title

exclude: ["README.md", "archives", "Gruntfile.js", "package.json", "node_modules", "less", "attachments", "cleanup", "import", "LICENSE"]

markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "post"
  -
    scope:
      path: "" # empty string for all files
    values:
      comments: "true"
